server:
  port: 8080

spring:
  application:
    name: palgoosam

  datasource:
    url: jdbc:mysql://localhost:3306/palgoosam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: palgoosam
    password: palgoosam_893

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  logging:
    level:
      org:
        hibernate:
          sql: debug
          type:
            descriptor:
              sql: trace